#!/bin/bash
# AXE Masternode Update Script for Ubuntu 16.04 LTS
#
# Script will attempt to Stop and remove old install and update the daemon
# and generate masternode private key unless specified in command line
#
# Usage:
# bash update.sh 
#

#Color codes
RED='\033[0;91m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

#Clear keyboard input buffer
function clear_stdin { while read -r -t 0; do read -r; done; }

#Delay script execution for N seconds
function delay { echo -e "${GREEN}Sleep for $1 seconds...${NC}"; sleep "$1"; }

#Stop daemon if it's already running

function stop_daemon {
    if pgrep -x 'axed' > /dev/null; then
        echo -e "${YELLOW}Attempting to stop axed${NC}"
        axe-cli stop
        delay 60
        if pgrep -x 'axe' > /dev/null; then
            echo -e "${RED}axed daemon is still running!${NC} \a"
            echo -e "${RED}Attempting to kill...${NC}"
            pkill axed
            delay 60
            if pgrep -x 'axed' > /dev/null; then
                echo -e "${RED}Can't stop axed! Reboot and try again...${NC} \a"
                exit 2
            fi
        fi
    fi
}

#Function detect_ubuntu

 if [[ $(lsb_release -d) == *16.04* ]]; then
   UBUNTU_VERSION=16
else
   echo -e "${RED}You are not running Ubuntu 16.04, Installation is cancelled.${NC}"
   exit 1

fi


#Check for updates

sudo DEBIAN_FRONTEND=noninteractive apt-get update -y
sudo apt-get -y upgrade
sudo apt-get -y dist-upgrade
sudo apt-get -y update

#remove existing daemon 
 stop_daemon
rm ~/AXE-MN-setup/axed axe-tx axe-cli
rm /usr/bin/axe*

#Installing Daemon
 cd ~
wget https://github.com/AXErunners/axe/releases/download/v1.4.0/axecore-1.4.0-x86_64-linux-gnu.tar.gz
rm ~/AXE-MN-setup/axed axe-tx axe-cli
tar -xzf axecore-1.4.0-x86_64-linux-gnu.tar.gz -C ~/AXE-MN-update
rm -rf axecore-1.4.0-x86_64-linux-gnu.tar.gz
 
 # Deploy binaries to /usr/bin
 sudo rm ~/AXE-MN-setup/axecore-1.4.0/bin/axe-qt
 sudo rm ~/AXE-MN-setup/axecore-1.4.0/bin/test*
 sudo cp ~/AXE-MN-setup/axecore-1.4.0/bin/axe* /usr/bin/
 sudo chmod 755 -R ~/AXE-MN-setup
 sudo chmod 755 /usr/bin/axe*
 

    #Starting daemon
    axed -daemon
echo -ne '[##                 ] (15%)\r'
sleep 10
echo -ne '[######             ] (30%)\r'
sleep 10
echo -ne '[########           ] (45%)\r'
sleep 10
echo -ne '[############       ] (67%)\r'
sleep 10
echo -ne '[################   ] (72%)\r'
sleep 10
echo -ne '[###################] (100%)\r'
echo -ne '\n'


echo -e 
"========================================================================
${YELLOW}Masternode Update is complete!${NC}
========================================================================"

clear_stdin
read -p "*** Press any key to continue ***" -n1 -s

echo -e "
${GREEN}...scroll up to see previous screens...${NC}
Here are some useful commands and tools for masternode troubleshooting:
========================================================================
To view masternode configuration produced by this script in axe.conf:
${YELLOW}cat ~/.axecore/axe.conf${NC}
Here is your axe.conf generated by this script:
-------------------------------------------------${YELLOW}"
cat ~/.axecore/axe.conf
echo -e "${NC}-------------------------------------------------
NOTE: To edit axe.conf, first stop the axed daemon,
then edit the axe.conf file and save it in nano: (Ctrl-X + Y + Enter),
then start the axed daemon back up:
             to stop:   ${YELLOW}axe-cli stop${NC}
             to edit:   ${YELLOW}axe ~/.axecore/axe.conf${NC}
             to start:  ${YELLOW}axed${NC}
========================================================================
To view AXE debug log showing all MN network activity in realtime:
             ${YELLOW}tail -f ~/.axecore/debug.log${NC}
========================================================================
To monitor system resource utilization and running processes:
                   ${YELLOW}htop${NC}
========================================================================
To view the list of peer connections, status of your masternode, 
sync status etc. in real-time, run the axemon.sh script:
                 ${YELLOW}axemon.sh${NC}
or just type 'node' and hit <TAB> to autocomplete script name.
========================================================================

Contact Twystidceed#4126 on discord if you need additional support
"
delay 30
# Run axemon.sh
axemon.sh

# EOF
